name: Python Linting Checks

on: [push, pull_request]

jobs:
  flake8-lint:
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flake8

      - name: Run linter
        run: |
          flake8 .