name: Run pytest tests

on: [push, pull_request]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest --doctest-modules flood_tool

      - name: Check installation
        run: |
            pip install -e .
